### ISSUE TITLE
PROCESOS qeu hago entre medias

### ISSUE THREAD

**Issue by MALR07** [MALR07/Web-TFG#2]
## Clonar el proyecto a mi maquina 

`git clone git@github.com:MALR07/Web-TFG.git`

![Image](https://github.com/user-attachments/assets/7bb46bf7-035b-46d9-8fe6-b33760d234e2)

## Creación del `docker-compose.yml`

```
services:
  # Base de datos (PostgreSQL)
  db:
    image: postgres:latest
    container_name: WEB-TFG-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=WEB-TFG-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   # Volumen persistente para la base de datos
    ports:
      - "5432:5432" 
    #networks:
      #- bar_network

```
_`./database/data:/var/lib/postgresql/data `asegurar que los datos de la base de datos sean persistentes. Esto significa que, incluso si el contenedor de PostgreSQL se reinicia o se elimina, los datos que se encuentran en esa ruta no se perderán. En lugar de guardar los datos en el contenedor (que podría borrarse), los datos se almacenan en el volumen de Docker, que es independiente del ciclo de vida de los contenedores._

### Mando push del archivo .`yml` 

![Image](https://github.com/user-attachments/assets/37318f4c-feed-4d12-bca3-6ee0aacaef5a)

### Configuración posgre 27/03

Hacemos docker-compose up para la base de datos posgre 

_(Actualización se cambio `container_name: WEB-TFG` a `container_name: WEB-TFG-db`)_

_(el error es que la version de docker que utilizo ya no hace falta que ponga la version)_

`WARN[0000] /home/malr-07/Escritorio/Web-TFG/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion `

![Image](https://github.com/user-attachments/assets/fce78fec-6378-4d79-80fb-dada9278c1ee)

Relizamos `docker ps` (para saber si esta todo bien)

![Image](https://github.com/user-attachments/assets/7afe26a2-328a-48cc-8bf1-6bf72ad6c917)

## Configuramos DBEAVER para utilizar nuestro base de datos

![Image](https://github.com/user-attachments/assets/292f2133-76f7-411c-a7b8-e0f6fa70d067)

### provisional subida posgre sin tablas 

![Image](https://github.com/user-attachments/assets/a738c791-f16f-4c05-ab85-419c70ac5c73)

### Acabo Base datos

![Image](https://github.com/user-attachments/assets/d1a129b7-d561-4e2a-91dc-b2801b35589b)

- Cambio contraseña base de datos  a `malr07@`

- Actualizar Rama main 

## Configuracion para Frontend y Backend de `docker-compose.yml`

```
services:
  # Frontend (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina local
    depends_on:
      - backend      # Depende del backend para que se inicie después

  # Backend (Node.js + Express)
  backend:
    build: ./backend
    ports:
      - "3001:3001"  # Mapea el puerto 3001 del contenedor al puerto 3001 de tu máquina local
    environment:
      - NODE_ENV=production
    depends_on:
      - db           # Depende de la base de datos para asegurarse que se inicie después

  # Base de datos (PostgreSQL)
  db:
    image: postgres:latest # Usa la última versión de la imagen oficial de PostgreSQL
    container_name: WEB-TFG-db # Nombre del contenedor de la base de datos
    environment:
      - POSTGRES_USER=user # Nombre de usuario para la base de datos
      - POSTGRES_PASSWORD=password # Contraseña para la base de datos
      - POSTGRES_DB=WEB-TFG-db # Nombre de la base de datos a crear
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   # Volumen persistente para la base de datos
    ports:
      - "5432:5432" # Mapea el puerto 5432 del contenedor al puerto 5432 de tu máquina local
    networks:
      - bar_network # Define una red personalizada para la comunicación entre los servicios
 # Redes
networks:
  bar_network:
    driver: bridge # Define una red personalizada llamada bar_network utilizando el driver de red 'bridge' (predeterminado)
```
----------------------------
### Instalacion NPM, node.js  y express

- Instalamos `npm` con `sudo apt install npm`_(necesario para poder utilizar node.js y luego instalar express)_
![Image](https://github.com/user-attachments/assets/271475ad-0a96-418a-a1d8-fdbcb74c140e)

- Con `npm init -y` inicializamos el proyecto y nos creara este archivo: 
![Image](https://github.com/user-attachments/assets/ac27cdeb-1e19-4a14-8ea7-e8d2bed30576)

- Ahora si instalamos **Express** con  `npm install express` _(Esto creará una carpeta `node_modules` y actualizará el archivo `package.json` con Express como dependencia.)_

![Image](https://github.com/user-attachments/assets/898ef831-bb98-4354-b6de-ba86ad11cfec)

- Creamos `server.js` que tendrá un código basico para que el servidor funcione 

```
// Importamos el módulo 'express', que es el framework para crear servidores en Node.js
const express = require('express');

// Creamos una instancia de la aplicación Express, que será nuestro servidor
const app = express();

// Definimos el puerto en el que el servidor va a escuchar
const PORT = 3001;

// Middleware
// Este middleware permite que el servidor entienda y procese datos en formato JSON
app.use(express.json());

// Definimos una ruta básica (la raíz '/') que responde con un mensaje
app.get('/', (req, res) => {
    res.send('¡El servidor está en funcionamiento!');
});

// Iniciamos el servidor y le decimos que escuche en el puerto definido (3001 en este caso)
// Cuando el servidor esté en funcionamiento, se ejecutará esta función y mostrará el mensaje en consola
app.listen(PORT, () => {
    console.log(`El servidor está en funcionamiento en http://localhost:${PORT}`);
});
```
Crearemos un archivo `.dockerignore` similar a `.gitignore` _(esto se debe a que no queremos que docker en este caso copie `node_modules` y archivos temporales, así reduciremos el tamaño de la imagen evitaremos problemas de seguridad y mejora la eficiencia)_
```
# Ignorar la carpeta de dependencias locales
node_modules/

# Ignorar el archivo de log de npm (se genera cuando hay errores de instalación)
npm-debug.log

```
- Construiremos la imagen del backend con `docker-compose build backend` (dado que solo tenia la base de datos construida)

![Image](https://github.com/user-attachments/assets/ceb93c6c-fa78-4cb2-a63f-1646ed14a5f0)

- Y por ultimo levantamos el servicio con `docker docker compose up -d `

![Image](https://github.com/user-attachments/assets/bb7e7912-63b2-48db-8f66-213f065ffb3d)

![Image](https://github.com/user-attachments/assets/d25af24b-f876-47f7-9370-bf0236e7e271)

### Nueva config `.yml`
```
services:
  # Frontend (React)
  #frontend:
    #build: ./frontend
    #ports:
     # - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina local
    #depends_on:
     # - backend      # Depende del backend para que se inicie después

  # Backend (Node.js + Express)
  backend:
    build: ./backend
    container_name: WEB-TFG-backend # Nombre del contenedor del backend
    ports:
      - "3001:3001"  # Mapea el puerto 3001 del contenedor al puerto 3001 de tu máquina local
    volumes:
      - ./backend:/usr/src/app  # Monta el directorio ./backend local dentro del contenedor en /usr/src/app 
    environment:
      - NODE_ENV=development # Establece el entorno como desarrollo (útil para nodemon) 
    depends_on:
      - db           # Depende de la base de datos para asegurarse que se inicie después
    networks:
      - bar_network            # Usar la red personalizada para la comunicación entre servicios

  # Base de datos (PostgreSQL)
  db:
    image: postgres:latest # Usa la última versión de la imagen oficial de PostgreSQL
    container_name: WEB-TFG-db # Nombre del contenedor de la base de datos
    environment:
      - POSTGRES_USER=user # Nombre de usuario para la base de datos
      - POSTGRES_PASSWORD=password # Contraseña para la base de datos
      - POSTGRES_DB=WEB-TFG-db # Nombre de la base de datos a crear
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   # Volumen persistente para la base de datos
    ports:
      - "5432:5432" # Mapea el puerto 5432 del contenedor al puerto 5432 de tu máquina local
    networks:
      - bar_network # Define una red personalizada para la comunicación entre los servicios
 # Redes
networks:
  bar_network:
    driver: bridge # Define una red personalizada llamada bar_network utilizando el driver de red 'bridge' (predeterminado)
```
Cambios aplicados 
- volumes en backend para poder hacer cambios locales y q se vayan al docker
- Development entorno como deasarrollador util para nodemon que instalare ahora
- container_name: WEB-TFG-backend  cambio de nombre
- Reinstale node.js archivos corruptos y actualice Express y nodemon

### Para ello vamos a conectar las tablas a nuestro backend

**Modelo `User.js` (Tabla users)**

 - `sequelize.define`: Define el modelo para la tabla **users**.

 - `DataTypes: Sequelize` ofrece varios tipos de datos como `INTEGER`, `STRING,` `TEXT`, etc., para cada columna.

 - `id_user`: La columna `id_user` es la clave primaria (`primaryKey`) y `autoincremental`.

  - **nombre, email, contrasena, rol**: Las otras columnas con las propiedades definidas (_por ejemplo, `allowNull: false` asegura que no pueden ser NULL)_.

 - `tableName`: 'users': Especificamos que la tabla se llama `users`.

 - `timestamps`: false: Deshabilitamos los campos por defecto `createdAt` y `updatedAt`, ya que no los necesitas en este caso.
 
```
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database'); // Importa la conexión

// Modelo para la tabla 'users'
const User = sequelize.define('User', {
  id_user: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  nombre: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  email: {
    type: DataTypes.STRING,
    unique: true,
    allowNull: false,
  },
  contrasena: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  rol: {
    type: DataTypes.STRING(20),
    allowNull: false,
    validate: {
      isIn: [['cliente', 'camarero']],
    },
  },
}, {
  tableName: 'users',  // Especifica el nombre de la tabla en la base de datos
  timestamps: false,    // Deshabilitamos los campos 'createdAt' y 'updatedAt'
});

module.exports = User;
```
**Modelo `Plato.js` (Tabla platos)**

- `id_plato`: La columna `id_plato` es la clave primaria y autoincremental.

- **nombre, descripcion, cantidad_disponible**: El nombre y la cantidad disponible son obligatorios (`allowNull: false`), y la cantidad tiene una validación para ser mayor o igual a 0 (min: 0).

- `timestamps: false:` De nuevo, deshabilitamos los campos `createdAt` y `updatedAt.`

```
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database'); // Importa la conexión

// Modelo para la tabla 'platos'
const Plato = sequelize.define('Plato', {
  id_plato: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  nombre: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  descripcion: {
    type: DataTypes.TEXT,
  },
  cantidad_disponible: {
    type: DataTypes.INTEGER,
    allowNull: false,
    validate: {
      min: 0,  // Asegura que la cantidad disponible sea mayor o igual a 0
    },
  },
}, {
  tableName: 'platos',
  timestamps: false,
});

module.exports = Plato;

```
**Modelo `Reserva.js` (Tabla reservas)**

- `id_reserva`: La columna `id_reserva` es la clave primaria y autoincremental.

-` id_usuario, id_plato, fecha_reserva, cantidad`: Estas son las columnas que almacenan el id del usuario, el id del plato, la fecha de la reserva y la cantidad reservada.

- **Relaciones**: Definimos que una **Reserva** pertenece a un **User** y a un **Plato**:

    - `Reserva.belongsTo(User, { foreignKey: 'id_usuario', targetKey: 'id_user' })`: Indica que Reserva está relacionada con User a través de `id_usuario`.

     - `Reserva.belongsTo(Plato, { foreignKey: 'id_plato', targetKey: 'id_plato' })`: Similar para la relación con Plato a través de id_plato.

```
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database'); // Importa la conexión
const User = require('./users');
const Plato = require('./platos');

// Modelo para la tabla 'reservas'
const Reserva = sequelize.define('Reserva', {
  id_reserva: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  id_usuario: {
    type: DataTypes.INTEGER,
    allowNull: false,
  },
  id_plato: {
    type: DataTypes.INTEGER,
    allowNull: false,
  },
  fecha_reserva: {
    type: DataTypes.DATE,
    allowNull: false,
  },
  cantidad: {
    type: DataTypes.INTEGER,
    allowNull: false,
    validate: {
      min: 1,  // Asegura que la cantidad sea al menos 1
    },
  },
}, {
  tableName: 'reservas',
  timestamps: false,
});

// Definir relaciones (relación entre reservas, usuarios y platos)
Reserva.belongsTo(User, { foreignKey: 'id_usuario', targetKey: 'id_user' });
Reserva.belongsTo(Plato, { foreignKey: 'id_plato', targetKey: 'id_plato' });

module.exports = Reserva;
```
### Sincronización de los Modelos (Opcional)

```
// Importamos los modelos (User, Plato y Reserva) para usarlos y realizar sincronización
const User = require('./models/users');
const Plato = require('./models/platos');
const Reserva = require('./models/reservas');

// Sincronización de los modelos con la base de datos
// Esto se asegura de que las tablas en la base de datos estén sincronizadas con nuestros modelos Sequelize
sequelize.sync({ force: false })  // 'force: false' evita que se eliminen y recreen las tablas si ya existen
  .then(() => {
    console.log('Las tablas están sincronizadas correctamente.');
  })
  .catch((error) => {
    console.error('Error al sincronizar las tablas:', error);
  });
```
### Probamos si actualiza las tablas y se conecta correctamente con

![Image](https://github.com/user-attachments/assets/a7628b39-476c-4be5-a787-897f22577cbf)

-------

### Actualización de archivos por no conexión de base de datos y node en docker
**.env**
```
# Esta es una variable de entorno para la base de datos
DB_NAME=WEB-TFG-db

# Usuario de la base de datos
DB_USER=user

# Contraseña de la base de datos
DB_PASSWORD=malr07@

# Nombre del contenedor de PostgreSQL (esto se usa para la conexión entre contenedores en Docker) (anteriormente localhost)
DB_HOST=WEB-TFG-db 

# Puerto de PostgreSQL (5432 es el puerto por defecto)
DB_PORT=5432
```
**database.js (se cambia **localhost** por **WEB-TFG-db)****

`host: process.env.DB_HOST || 'WEB-TFG-db',  // Dirección del servidor de PostgreSQL`

### Actualización `server.js`
```
// Importamos los módulos necesarios
const express = require('express');
const session = require('express-session');
const passport = require('./config/passport');  
const cors = require('cors');
const dotenv = require('dotenv');
const sequelize = require('./config/database'); // Importamos la instancia de Sequelize configurada en 'database.js

// Importamos los modelos (User, Plato y Reserva) para usarlos y realizar sincronización
const User = require('./models/users');
const Plato = require('./models/platos');
const Reserva = require('./models/reservas');

// Cargar variables de entorno desde el archivo .env
dotenv.config();

// Creamos una instancia de la aplicación Express, que será nuestro servidor
const app = express();

// Definimos el puerto en el que el servidor va a escuchar
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());  // Habilitar CORS
app.use(express.json()); // Este middleware permite que el servidor entienda y procese datos en formato JSON
app.use(express.urlencoded({ extended: true }));  // Analizar cuerpos de solicitudes URL-encoded

// Configuración de la sesión
app.use(session({
  secret: process.env.SESSION_SECRET || 'secret',  // Secreto para firmar la sesión
  resave: false,
  saveUninitialized: false,
  cookie: { secure: false }  // Configura 'secure: true' si usas HTTPS
}));

// Inicializamos Passport.js
app.use(passport.initialize());
app.use(passport.session());

// Verificamos la conexión con la base de datos
sequelize.authenticate()
  .then(() => {
    console.log('Conexión a la base de datos exitosa!');
  })
  .catch((error) => {
    console.error('No se pudo conectar a la base de datos:', error);
  });

// Sincronización de los modelos con la base de datos
// Esto se asegura de que las tablas en la base de datos estén sincronizadas con nuestros modelos Sequelize
sequelize.sync({ force: false })  // 'force: false' evita que se eliminen y recreen las tablas si ya existen
  .then(() => {
    console.log('Las tablas están sincronizadas correctamente.');
  })
  .catch((error) => {
    console.error('Error al sincronizar las tablas:', error);
  });

// Ruta de login con Passport.js
app.post('/login', passport.authenticate('local', { 
  successRedirect: '/dashboard', // Si el login es exitoso, redirigir al dashboard
  failureRedirect: '/login',     // Si falla, redirigir a la página de login
  failureFlash: true             // Si hay errores, los muestra en el flash
}));

// Ruta de registro (esto depende de si decides implementarla)
app.post('/register', async (req, res) => {
  const { nombre, email, contrasena, rol } = req.body;

  try {
    // Crear un nuevo usuario
    const user = await User.create({
      nombre,
      email,
      contrasena,  // Asegúrate de encriptar la contraseña antes de guardarla
      rol
    });

    res.status(201).json({ message: 'Usuario registrado exitosamente', user });
  } catch (error) {
    console.error('Error al registrar el usuario:', error);
    res.status(500).json({ message: 'Error al registrar el usuario' });
  }
});

// Ruta de dashboard (sólo accesible después de login exitoso)
app.get('/dashboard', (req, res) => {
  if (!req.isAuthenticated()) {
    return res.redirect('/login');
  }
  res.send('Bienvenido al dashboard');
});

// Definimos una ruta básica (la raíz '/') que responde con un mensaje
app.get('/', (req, res) => {
    res.send('¡El servidor está en funcionamiento!');
});

// Iniciamos el servidor y le decimos que escuche en el puerto definido (3001 en este caso)
// Cuando el servidor esté en funcionamiento, se ejecutará esta función y mostrará el mensaje en consola
app.listen(PORT, () => {
    console.log(`El servidor está en funcionamiento en http://localhost:${PORT}`);
});
```
# Explicación de los cambios realizados
- **passport y express-session**: Están configurados correctamente para manejar la autenticación. Usamos `passport.initialize()` y `passport.session()` para integrar **Passport** en las rutas y la gestión de sesiones.

- Conexión a la base de datos y sincronización de modelos (`sequelize.authenticate()` y `sequelize.sync()`): Estos métodos aseguran que la conexión a la base de datos de PostgreSQL esté funcionando y que las tablas estén sincronizadas.

- **Rutas de login y registro**:

  - **/login**: Aquí se maneja la autenticación con Passport usando la estrategia local. Si el login es exitoso, el usuario es redirigido al **/dashboard**; si falla, se redirige a **/login**.

  - **/register**: Ruta para crear un nuevo usuario. Aquí deberías agregar el proceso de encriptar la contraseña antes de almacenarla, que puede hacerse usando **bcryptjs**.

- **Middleware de sesión y CORS**: Esto es para asegurarnos de que las sesiones estén manejadas correctamente y que las solicitudes **CORS** sean permitidas.

### ¿Qué falta agregar?

> Encriptación de contraseñas: Asegúrate de que las contraseñas se encripten antes de guardarlas en la base de datos. Puedes usar bcryptjs para esto.

### Próximos pasos

> Registro de usuarios: Si aún no lo has hecho, debes encriptar la contraseña del usuario antes de guardarla en la base de datos en la ruta /register.
> Autorización de roles: Puedes agregar middleware adicional para manejar la autorización de roles en rutas específicas (por ejemplo, asegurarte de que solo los administradores accedan a ciertas rutas).

> _(Con esto deveria de estar configurado)_

# Passport.js Listo ✅ 

# Configuración de **bcryptjs** para encriptar contraseñas de los usuarios

- Para encriptar las contraseñas de los usuarios, utilizamos **bcryptjs.** Vamos a agregar la encriptación de contraseñas en el modelo de usuarios (users)

### Actualizar el modelo User para encriptar contraseñas

- Y para eso añadiremos esto a nuestro archivo `users.js`

```
const bcrypt = require('bcryptjs'); // Importar bcrypt para la comparación de contraseñas

// Hook para encriptar la contraseña antes de guardar
User.beforeCreate(async (user) => {
  const salt = await bcrypt.genSalt(10);
  user.contrasena = await bcrypt.hash(user.contrasena, salt);
});

// Método para comparar contraseñas
User.prototype.comparePassword = function (candidatePassword) {
  return bcrypt.compare(candidatePassword, this.contrasena);
};
```
### Cambios Dia 7/04/25
# Configuración de JSON Web Tokens (JWT)

 Se puede usar JWT para sesiones sin necesidad de guardar información en la base de datos, usando tokens que se envían al cliente. Aquí vamos a implementar un método para generar un JWT después del login.

- Este código genera un token JWT que contiene el **id_user** y lo devuelve al cliente. El siguiente código estará en el archivo en la carpeta config y creamos el archivo `routes.js`

```
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const { User } = require('./models/users'); // Asegúrate de importar tu modelo de usuario

// Ruta de login
app.post('/login', async (req, res) => {
  const { email, contrasena } = req.body;

  // Buscar usuario en la base de datos
  const user = await User.findOne({ where: { email } });

  if (!user) {
    return res.status(401).json({ message: 'Usuario no encontrado' });
  }

  // Comparar la contraseña
  const isMatch = await bcrypt.compare(contrasena, user.contrasena);
  if (!isMatch) {
    return res.status(401).json({ message: 'Contraseña incorrecta' });
  }

  // Crear el token JWT
  const token = jwt.sign({ id_user: user.id_user }, process.env.JWT_SECRET, { expiresIn: '1h' });

  return res.json({ message: 'Login exitoso', token });
});
```
# Configuración Nodemailer para recuperación de contraseñas

- Crearemos un archivo llamado `mailer.js`en la carpeta `config` para configurar el servicio de envío de correos electrónicos (En esta función, se envía un correo electrónico con un enlace para restablecer la contraseña)

```
const nodemailer = require('nodemailer');

// Crear un transporte para enviar correos electrónicos
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,  // Tu correo de Gmail
    pass: process.env.EMAIL_PASS,  // Tu contraseña de Gmail (o una contraseña de aplicación)
  }
});

// Función para enviar correos de recuperación de contraseña
const sendPasswordRecoveryEmail = (email, token) => {
  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: email,
    subject: 'Recuperación de contraseña',
    text: `Haz clic en el siguiente enlace para recuperar tu contraseña: ${process.env.BASE_URL}/reset-password?token=${token}`,
  };

  return transporter.sendMail(mailOptions);
};

module.exports = sendPasswordRecoveryEmail;
```

 ### Añadiremos al archivo `.env` para almacenar la siguientes variable de entorno:

 ```
 # Configuración de JWT (JSON Web Token)
JWT_SECRET=mi_secreto_jwt
 
 # Configuración para el envío de correos electrónicos
 EMAIL_HOST=smtp.gmail.com
 EMAIL_PORT=587
 EMAIL_USER=tu_correo@gmail.com
 EMAIL_PASS=tu_contraseña

 # Configuración del servidor Express
 PORT=3001

 # Configuración de la sesión de Express
SESSION_SECRET=mi_secreto_sesion
 ```

- JWT_SECRET:
 Es necesario para la autenticación basada en tokens JWT, que pueden ser utilizados para mantener sesiones de usuario seguras.

- Variables de Email:
 Son necesarias si implementamos una función de recuperación de contraseñas por correo electrónico (como el ejemplo con Nodemailer). Necesitarás un servidor SMTP válido para enviar correos.
 
- PORT:
 Define el puerto en el que se ejecuta el servidor Express. Si no especificamos este valor, el servidor probablemente correrá en el puerto 3000 por defecto.

- SESSION_SECRET:
Si usamos express-session para gestionar las sesiones del usuario, este secreto es necesario para proteger y verificar las cookies de sesión.

Cambios server.js
```
// Importamos los módulos necesarios
const express = require('express');
const session = require('express-session');
const passport = require('./config/passport');  
const cors = require('cors');
const dotenv = require('dotenv');
const jwt = require('jsonwebtoken');  // Para crear y verificar tokens JWT
const bcrypt = require('bcryptjs');  // Para encriptar contraseñas
const sendPasswordRecoveryEmail = require('./config/mailer'); // Para el envío de correos
const sequelize = require('./config/database'); // Configuración de la base de datos con Sequelize

// Importar modelos
const User = require('./models/users');
const Plato = require('./models/platos');
const Reserva = require('./models/reservas');

// Cargar variables de entorno desde el archivo .env
dotenv.config();

// Crear una instancia de la aplicación Express
const app = express();

// Definir el puerto en el que el servidor va a escuchar
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());  // Habilitar CORS
app.use(express.json()); // Este middleware permite que el servidor entienda y procese datos en formato JSON
app.use(express.urlencoded({ extended: true }));  // Analizar cuerpos de solicitudes URL-encoded

// Configuración de la sesión
app.use(session({
  secret: process.env.SESSION_SECRET || 'secret',  // Secreto para firmar la sesión
  resave: false,
  saveUninitialized: false,
  cookie: { secure: false }  // Configura 'secure: true' si usamos HTTPS
}));

// Inicializamos Passport.js
app.use(passport.initialize());
app.use(passport.session());

// Verificamos la conexión con la base de datos
sequelize.authenticate()
  .then(() => {
    console.log('Conexión a la base de datos exitosa!');
  })
  .catch((error) => {
    console.error('No se pudo conectar a la base de datos:', error);
  });

// Sincronización de los modelos con la base de datos
sequelize.sync({ force: false })  // 'force: false' evita que se eliminen y recreen las tablas si ya existen
  .then(() => {
    console.log('Las tablas están sincronizadas correctamente.');
  })
  .catch((error) => {
    console.error('Error al sincronizar las tablas:', error);
  });

// Ruta de login con Passport.js
app.post('/login', passport.authenticate('local', { 
  successRedirect: '/dashboard', // Si el login es exitoso, redirigir al dashboard
  failureRedirect: '/login',     // Si falla, redirigir a la página de login
  failureFlash: true             // Si hay errores, los muestra en el flash
}));

// Ruta de registro
app.post('/register', async (req, res) => {
  const { nombre, email, contrasena, rol } = req.body;

  try {
    // Crear un nuevo usuario
    const user = await User.create({
      nombre,
      email,
      contrasena,  // Asegúrate de encriptar la contraseña antes de guardarla
      rol
    });

    res.status(201).json({ message: 'Usuario registrado exitosamente', user });
  } catch (error) {
    console.error('Error al registrar el usuario:', error);
    res.status(500).json({ message: 'Error al registrar el usuario' });
  }
});

// Ruta de dashboard (sólo accesible después de login exitoso)
app.get('/dashboard', (req, res) => {
  if (!req.isAuthenticated()) {
    return res.redirect('/login');
  }
  res.send('Bienvenido al dashboard');
});

// Ruta para solicitar la recuperación de contraseña (enviar un correo con el token)
app.post('/forgot-password', async (req, res) => {
  const { email } = req.body;
  try {
    // Buscar al usuario por correo
    const user = await User.findOne({ where: { email } });

    if (!user) {
      return res.status(404).json({ message: 'Correo no encontrado' });
    }

    // Generar un token para la recuperación de la contraseña
    const token = jwt.sign({ id_user: user.id_user }, process.env.JWT_SECRET, { expiresIn: '1h' });

    // Enviar correo con el token
    await sendPasswordRecoveryEmail(email, token);

    res.status(200).json({ message: 'Correo enviado con éxito para recuperar la contraseña' });
  } catch (error) {
    console.error('Error al solicitar recuperación de contraseña:', error);
    res.status(500).json({ message: 'Error al enviar el correo' });
  }
});

// Ruta para restablecer la contraseña
app.post('/reset-password', async (req, res) => {
  const { token, newPassword } = req.body;

  try {
    // Verificar el token
    const decoded = jwt.verify(token, process.env.JWT_SECRET);

    // Buscar al usuario por su id_user
    const user = await User.findOne({ where: { id_user: decoded.id_user } });

    if (!user) {
      return res.status(404).json({ message: 'Usuario no encontrado' });
    }

    // Encriptar la nueva contraseña
    const salt = await bcrypt.genSalt(10);
    user.contrasena = await bcrypt.hash(newPassword, salt);

    // Guardar la nueva contraseña
    await user.save();

    res.status(200).json({ message: 'Contraseña restablecida con éxito' });
  } catch (error) {
    console.error('Error al restablecer la contraseña:', error);
    res.status(500).json({ message: 'Error al restablecer la contraseña' });
  }
});

// Definimos una ruta básica (la raíz '/') que responde con un mensaje
app.get('/', (req, res) => {
    res.send('¡El servidor está en funcionamiento!');
});

// Iniciamos el servidor y le decimos que escuche en el puerto definido (3001 en este caso)
app.listen(PORT, () => {
    console.log(`El servidor está en funcionamiento en http://localhost:${PORT}`);
});
```
